### ISSUE TITLE
Weather is showed 0° all the time

### ISSUE THREAD

**Issue by carmenfdezb** [kimmoli/toholed#15]
Weather is showed 0° all the time since I updated to 0.4.16

**Comment by kimmoli** [comment]
Sailfish-weather? If the events-view weather "widget" shows something else, then it is a bug.

**Comment by carmenfdezb** [comment]
Hi, kimmoli!
No, I use Meecast. This morning the weather is showed correctly. I will take a look today, maybe it's a false alarm and there's not bug

**Comment by kimmoli** [comment]
ok @CODeRUS  is responsible of Meecast support, i use only sailfish weather.

**Comment by CODeRUS** [comment]
on which version? did @kimmoli pushed latest commits to release?

**Comment by carmenfdezb** [comment]
On 0.4.16. But it seems it's working fine ;)

**Comment by kimmoli** [comment]
Closing this as "not a bug"

**Comment by carmenfdezb** [comment]
I think I've detected when it happens: when Meecast displays min./max. temperature instead of exact temperature.

![paint-03022016-222835](https://cloud.githubusercontent.com/assets/6286776/12797809/293c2ee4-cac6-11e5-836d-8faf577889a4.jpg)
![screenshot-16-02-02-22-35-01](https://cloud.githubusercontent.com/assets/6286776/12797814/352e0326-cac6-11e5-9412-3a97f2f67505.png)

**Comment by carmenfdezb** [comment]
I'm not sure but I would swear it didn't happen before
