### ISSUE TITLE
Sailorgram notifications

### ISSUE THREAD

**Issue by carmenfdezb** [kimmoli/toholed#16]
Could you add Sailorgram notifications? Since Whatsup isn't working fine, I'm sure I will move to Telegram soon.

**Comment by kimmoli** [comment]
Implemented in ca5875d2982f5c61559c9b9b167a98f917ee4910

**Comment by carmenfdezb** [comment]
Thank you very much!! You make me very happy today ;)

**Comment by kimmoli** [comment]
http://repo.merproject.org/obs//home:/kimmoli:/tohs/sailfish_latest_armv7hl/armv7hl/harbour-ambience-toholed-0.4.17-30.1.armv7hl.rpm
