### ISSUE TITLE
TOHOLED frozen during phone upgrade

### ISSUE THREAD

**Issue by ghost** [kimmoli/toholed#4]
During upgrade to Yliaavanlampi I noticed that TOHOLED clock screen was frozen in time around upgrading started. I fired up the TOHOLED app and it showed, what I understood, that TOHOLED should display "update time" screen with SailfisOS logo.

I was running deamon v0.4.0

**Comment by kimmoli** [comment]
Hopefully fixed by f2aaf2bf11928c4550462a
Released in 0.4.3
